project:
  type: website
  output-dir: docs

website:
  title: "Yuxi Jin"
  favicon: images/logo-site.png
  navbar:
    background: "#6fa27d"
    foreground: "white"
    style: "docked"
    search: true
    left:
      - href: index.qmd
        text: Home
      - contact.qmd
  cookie-consent:
      type: express
      palette: dark

format:
  html:
    theme: 
      - simplex
      - simplex.scss
    css: styles.css      
    toc: true

editor: visual

